Show menu items
CraftAcademy/slowfood-api-team-2-april-2020 pull request #2
Opened 2020-05-05 11:33 UTC by ViaMarcus

### Show menu items
This PR adds the ability for the API to serve menu items from the database.
It also adds the menu_item model, and tests for the model.
The endpoint is GET '/api/v1/menu_items'
It takes no params and returns
`{ items: [<MenuItem>,<MenuItem>]}` where each `MenuItem` has id, name, description and price.
[PT Card](https://www.pivotaltracker.com/story/show/172642043)

2020-05-05 11:42 UTC, kermit-klein reviewed
It works!

2020-05-05 14:41 UTC, oliverochman requested changes

2020-05-05 14:41 UTC, oliverochman commented on app/controllers/api/v1/menu_items_controller.rb
> +	def index
please fix indentation in this file

2020-05-05 14:41 UTC, oliverochman commented on spec/requests/api/v1/menu_items_spec.rb
> +    let!(:food1) { create(:menu_item, name: 'Pickled Egg', description: 'An egg that is in a reeeeal pickle!', price: 69) }
you dont test any of the attributes for these menu items. 

please refactor it to

```
let!(:menu_items) { 3.times { create(:menu_item) } }
```

2020-05-05 14:41 UTC, oliverochman commented on spec/requests/api/v1/menu_items_spec.rb
> +        describe 'should return a response with' do
no reason to have these tests in a separate describe block.

2020-05-05 14:41 UTC, oliverochman commented on spec/requests/api/v1/menu_items_spec.rb
> +            let(:json_response) { JSON.parse(response.body) }
please extract this helper method from this file

2020-05-05 14:41 UTC, oliverochman commented on spec/requests/api/v1/menu_items_spec.rb
> +                expect(json_response["items"][0]["name"]).to eq food1.name
instead of testing what it equals to you can test that it includes `["name"]`

2020-05-05 14:42 UTC, oliverochman requested changes

2020-05-05 14:42 UTC, oliverochman commented on app/controllers/api/v1/menu_items_controller.rb
> +		render json: { items: items }
if the models name is menu items, you should name the key to that as well

2020-05-05 15:08 UTC, hashtagDora reviewed
I will do the changes

2020-05-06 08:06 UTC, oliverochman approved these changes

2020-05-06 08:06 UTC, merged